version: '3'
services:
    nginx:
        build: ./requirements/nginx/
        env_file:
            - .env
        ports:
            - "443:443"
        networks:
            - backend
        depends_on:
            - wordpress
        volumes:
            - wp-data:/www/wordpress

    mariadb:
        build: ./requirements/mariadb
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql

    wordpress:
        build: ./requirements/wordpress
        env_file:
            - .env
        ports:
            - "9000:9000"
        expose:
            - 9000
        networks:
            - backend
        volumes:
            - wp-data:/www/wordpress

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            device: "/home/mymik/data/db-data"
            o: bind
    wp-data:
        driver: local
        driver_opts:
            type: none
            device: "/home/mymik/data/wp-data"
            o: bind
            #networks:
            # backend:
            #driver: bridge

networks:
    backend:
            #driver: bridge
