version: '3'
services:
    nginx:
        build: ./requirements/nginx/
        env_file:
            - .env
        ports:
            - "443:443"
    mysql:
        build: ./requirements/mariadb
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            device: "/home/mymik/data/db-data"
            o: bind

