version: '3'
services:
    nginx:
        build: ./requirements/nginx/
        env_file:
            - .env
        ports:
            - "443:443"
        networks:
            - backend
        depends_on:
            - wordpress
        volumes:
            - mwp-data:/www/wordpress

    mariadb:
        build: ./requirements/mariadb
        env_file:
            - .env
        networks:
            - backend
        volumes:
            - mdb-data:/var/lib/mysql

    wordpress:
        build: ./requirements/wordpress
        env_file:
            - .env
        networks:
            - backend
        volumes:
            - mwp-data:/www/wordpress

    adminer:
        build: ./requirements/bonus/adminer
        networks:
            - backend
        ports:
            - "5000:5000"
    
    ftp:
        build: ./requirements/bonus/ftp
        env_file:
            - .env
        volumes:
            - mwp-data:/home/user
        ports:
            - "21:21"
            - "21000:21000"

    redis:
        build: ./requirements/bonus/redis
        networks:
            - backend


volumes:
    mdb-data:
        driver: local
        driver_opts:
            type: none
            device: "/home/m/data/db-data"
            o: bind
    mwp-data:
        driver: local
        driver_opts:
            type: none
            device: "/home/m/data/wp-data"
            o: bind
            #networks:
            # backend:
            #driver: bridge

networks:
    backend:
            driver: bridge
