FROM alpine

RUN apk add --no-cache go

#ENV GOROOT /usr/lib/go
#ENV GOPATH /go
#ENV PATH /go/bin:$PATH
#RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

#RUN go get -u github.com/Masterminds/glide/...

#WORKDIR $GOPATH

